# Generated by Django 6.0.3 on 2026-04-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatdata',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heatdata',
            name='riskLevel',
            field=models.CharField(default='Moderate', max_length=50),
            preserve_default=False,
        ),
    ]
