# Generated by Django 6.0.3 on 2026-04-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0002_heatdata_name_heatdata_risklevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.FloatField()),
                ('riskLevel', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='heatdata',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='heatdata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='heatdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='heatdata',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='heatdata',
            name='riskLevel',
            field=models.CharField(max_length=20),
        ),
    ]
